language: php

matrix:
  include:
    - php: 7.3
    - php: 7.2
    - php: 7.1
    - php: 7.0
    - php: 5.6
    - php: 5.5
      dist: trusty
    - php: 5.4
      dist: trusty
    - php: 5.3
      dist: precise

before_script:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer self-update
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - vendor/bin/test-reporter --coverage-report coverage.xml

addons:
  code_climate:
    repo_token: bd9efc00e154e95e68702c987c338d26dade817a2724b055f8eefa670c971661
